name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
  CLIENT_A: ${{ secrets.CLIENT_A }}

permissions:
  id-token: write  # for requesting the jwt token from GitHub's OIDC provider.
  contents: read   # for checking out the code in the repo
  security-events: write

jobs:
  build_and_scan:
    # set permissions for oicd (open id connect) authentication with aws
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: checkout repository code
        uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_dev.txt

      - name: run pytest
        run: pytest
        env:
          CORS_ORIGINS: 'http://localhost:3000,http://127.0.0.1:3000'
          PYTEST_RUN: true

      # static analysis and dependency scanning with snyk
      - name: run snyk sast
        uses: snyk/actions/python@master
        with:
          command: test
          args: --severity-threshold=high --policy-path=.synk --python-version=3.12 --skip-unresolved --file=requirements.txt
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: run snyk sca
        uses: snyk/actions/python@master
        with:
          command: code test
          args: --severity-threshold=high --policy-path=.synk --python-version=3.12 --skip-unresolved --file=requirements.txt
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # config aws credentials using oidc
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION_NAME }}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }} # iam role for github actions
          role-session-name: GitHubActions-Build-Test-${{ github.run_id }}

      - name: test aws access
        run: |
          echo "... testing aws authentication ..."
          aws sts get-caller-identity
          echo "✅ oidc authentication successful"

      # trigger aws codebuild to start the project 'pj-sales-pred'
      - name: trigger aws codebuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: ${{ secrets.CODEBUILD_PROJECT }}
          source-version: ${{ github.sha }}
          environment-variables-override: |
            [
              {
                "name": "GITHUB_SHA",
                "value": "${{ github.sha }}"
              },
              {
                "name": "LAMBDA_FUNCTION_NAME",
                "value": "${{ env.LAMBDA_FUNCTION_NAME }}"
              }
            ]
