name: Deploy Containerized Lambda

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to deploy from'
        required: true
        default: 'develop'
        type: choice
        options:
          - main
          - develop

env:
  BRANCH_NAME: "main"
  GITHUB_SHA: ${{ github.sha }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    # configure aws credentials using oicd
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ secrets.AWS_REGION_NAME }}
        role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}

    - name: set environment variables
      run: |
        echo "BRANCH_NAME=${{ github.event.inputs.branch }}" >> $GITHUB_ENV
        echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV

    - name: check lambda function exists
      run: |
        aws lambda get-function --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} --region ${{ secrets.AWS_REGION_NAME }}

    # retrieve image tag from aws param store
    - name: retrieve image tag from aws param store
      id: get_tag
      run: |
        IMAGE_TAG=$(aws ssm get-parameter --name "/my-app/image-tag" --query "Parameter.Value" --output text)
        echo "... retrieved IMAGE_TAG: $IMAGE_TAG"
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    # construct image url with image tag
    - name: construct image uri
      id: get_image
      run: |
        ECR_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION_NAME }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}
        IMAGE_URI_WITH_TAG="${ECR_URI}:${{ env.IMAGE_TAG }}"

        echo "ECR_URI=$ECR_URI"
        echo "IMAGE_URI_WITH_TAG=$IMAGE_URI_WITH_TAG" >> $GITHUB_ENV

    # update the lambda function
    - name: update lambda function with the image retrieved
      run: |
        if [[ "${{ env.IMAGE_TAG }}" ]]; then
          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --region ${{ secrets.AWS_REGION_NAME }} \
            --image-uri ${{ env.IMAGE_URI_WITH_TAG }}
        else
          echo "... couldn't find existing image. create a new one ..."
        fi

    # # when no image tags are found, build one from scratch
    # - name: start codebuild for container build
    #   if: ${{ !env.IMAGE_TAG }}
    #   uses: aws-actions/aws-codebuild-run-build@v1
    #   id: codebuild
    #   with:
    #     project-name: ${{ secrets.CODEBUILD_PROJECT }}
    #     source-version-override: ${{ github.event.inputs.branch }}
    #     env-vars-for-codebuild: |
    #       [
    #         {
    #           "name": "GITHUB_REF",
    #           "value": "refs/heads/${{ github.event.inputs.branch }}"
    #         },
    #         {
    #           "name": "BRANCH_NAME",
    #           "value": "${{ env.BRANCH_NAME }}"
    #         },
    #         {
    #           "name": "ECR_REPOSITORY_NAME",
    #           "value": "${{ secrets.ECR_REPOSITORY }}"
    #         },
    #         {
    #           "name": "LAMBDA_FUNCTION_NAME",
    #           "value": "${{ secrets.LAMBDA_FUNCTION_NAME }}"
    #         }
    #       ]

    # # update the lambda function with the new image created
    # - name: update lambda function with a new image
    #   if: ${{ !env.IMAGE_TAG }}
    #   run: |
    #     aws lambda update-function-code \
    #       --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
    #       --region ${{ secrets.AWS_REGION_NAME }} \
    #       --image-uri "$IMAGE_URI_WITH_TAG"


    - name: verify lambda updates
      run: |
        CURRENT_IMAGE=$(aws lambda get-function \
          --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
          --region ${{ secrets.AWS_REGION_NAME }} \
          --query 'Code.ImageUri' \
          --output text)

        if [[ $CURRENT_IMAGE == *"${{ github.event.inputs.branch }}"* ]]; then
          echo "✅ lambda function successfully updated with new image"
        else
          echo "❌ lambda function update may have failed"
          exit 1
        fi

    - name: test lambda function
      if: github.event.inputs.branch == 'main'
      run: |
        aws lambda invoke \
          --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
          --region ${{ secrets.AWS_REGION_NAME }} \
          --payload '{"test": true}' \
          --cli-binary-format raw-in-base64-out \
          response.json

        cat response.json

    - name: update lambda environment variables (if needed)
      if: github.event.inputs.branch == 'main'
      run: |
        aws lambda update-function-configuration \
          --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
          --region ${{ secrets.AWS_REGION_NAME }} \
          --environment Variables='{
            "ENVIRONMENT": "production",
            "VERSION": "${{ github.sha }}",
            "DEPLOY_TIME": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"
          }'

    - name: cleanup
      if: always()
      run: |
        echo "=== Cleanup ==="
        rm -f response.json
        echo "✅ Cleanup completed"
